stages:
  - test

test-hw0:
  stage: test
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y build-essential make valgrind
  script:
    - cd hw0
    - make
    - './main | tee output.txt'
    - 'test "$(tr -d "\n\r" < output.txt)" = "42"'